# Generated by Django 2.2 on 2020-09-13 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, null=True)),
                ('file_data', models.FileField(upload_to='uploads/%Y/%m/%d/')),
            ],
        ),
    ]
